name: Image Optimizer
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'

jobs:
  image_optimizer:
    name: Image Optimizer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Optimizing Images
        uses: crush-pics/crush-pics-github-action@v1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.CRUSH_API_KEY }}
